version: '3.9'
services:
 serverApp:
  build:
  args:
    -NODE_ENV=development
  context:
    context: ./server
    Dockerfile: Dockerfile
  ports:
    - "8080:8080"
    
    environment:
     ENV POSTGRES_DB mydatabase
     ENV POSTGRES_USER myuser
     ENV POSTGRES_PASSWORD mypassword
    
